/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaccia;

import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.PdfStamper;
import fattura.Fattura;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Sara
 */
public class PercorsoFattura extends javax.swing.JDialog {
    private String cliente,data;
    private AtomicInteger numerofattura;
    /**
     * Creates new form PercorsoFattura
     */
    public PercorsoFattura(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public PercorsoFattura(java.awt.Frame parent,boolean modal,String clienteric,String dataric,AtomicInteger numeroric){
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.cliente=clienteric;
        this.data=dataric;
        this.numerofattura=numeroric;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser2 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jFileChooser2.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser2.setCurrentDirectory(new java.io.File("C:\\Users\\Sara\\Desktop\\CherryQueenManager"));
        jFileChooser2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFileChooser2MouseClicked(evt);
            }
        });
        jFileChooser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jFileChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jFileChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFileChooser2MouseClicked
        int i=jFileChooser2.showSaveDialog(this);
        switch(i){
            case JFileChooser.APPROVE_OPTION:
            {
                try {
            String percorso=jFileChooser2.getSelectedFile().getAbsolutePath();
            String FILEIN ="C:/Users/Sara/Desktop/CherryQueenManager/PDF/TemplateInvoice.pdf";           
            PdfReader pdfReader = new PdfReader(FILEIN);
            PdfStamper pdfStamper= new PdfStamper(pdfReader,new FileOutputStream(percorso));
            Fattura fat=new Fattura(cliente,data);
            fat.setFattura(cliente,data,numerofattura,pdfStamper);
            JOptionPane.showMessageDialog(null,"Fatto");
            
        } catch (IOException|DocumentException|SQLException ex) {
            Logger.getLogger(PercorsoFattura.class.getName()).log(Level.SEVERE, null, ex);
        }
                break;
            }
            case JFileChooser.CANCEL_OPTION:
                break;
        }     
    }//GEN-LAST:event_jFileChooser2MouseClicked

    private void jFileChooser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser2ActionPerformed
        // TODO add your handling code here:
        int i=jFileChooser2.showSaveDialog(this);
        switch(i){
            case JFileChooser.APPROVE_OPTION:
            {
                try {
            String percorso=jFileChooser2.getSelectedFile().getAbsolutePath();
            String FILEIN ="C:/Users/Sara/Desktop/CherryQueenManager/PDF/TemplateInvoice.pdf";           
            PdfReader pdfReader = new PdfReader(FILEIN);
            PdfStamper pdfStamper= new PdfStamper(pdfReader,new FileOutputStream(percorso));
            Fattura fat=new Fattura(cliente,data);
            fat.setFattura(cliente,data,numerofattura,pdfStamper);
            JOptionPane.showMessageDialog(null,"Fatto");
            
        } catch (IOException|DocumentException|SQLException ex) {
            Logger.getLogger(PercorsoFattura.class.getName()).log(Level.SEVERE, null, ex);
        }
                break;
            }
            case JFileChooser.CANCEL_OPTION:
                break;
        }     
                       
    }//GEN-LAST:event_jFileChooser2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser2;
    // End of variables declaration//GEN-END:variables
}
